"""empty message

Revision ID: 20b5ae16781f
Revises: 
Create Date: 2021-12-28 23:45:39.247420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20b5ae16781f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('p_image_address', sa.String(length=125), nullable=True))
    op.add_column('product', sa.Column('p_image_name', sa.String(length=125), nullable=True))
    op.drop_column('product', 'p_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('p_image', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('product', 'p_image_name')
    op.drop_column('product', 'p_image_address')
    # ### end Alembic commands ###
