"""empty message

Revision ID: 2889766e2b28
Revises: 8cd90a2ef0f8
Create Date: 2022-01-06 18:33:32.182977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2889766e2b28'
down_revision = '8cd90a2ef0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity_in_store', sa.Integer(), nullable=True))
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product', 'quantity_in_store')
    # ### end Alembic commands ###
