"""empty message

Revision ID: 6f44d2090303
Revises: 832fa635aa33
Create Date: 2022-01-06 16:43:22.842236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f44d2090303'
down_revision = '832fa635aa33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('staff', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('vendor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vendor')
    op.drop_column('user', 'staff')
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###
