"""empty message

Revision ID: 8cd90a2ef0f8
Revises: 6f44d2090303
Create Date: 2022-01-06 16:43:55.855477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd90a2ef0f8'
down_revision = '6f44d2090303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('brand', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'brand')
    # ### end Alembic commands ###
